language: node_js
node_js:
- stable
before_script:
- npm i
- npm run build
- wget -O docs/wallet/index.html https://github.com/monya-wallet/monya-wallet.github.io/raw/master/wallet/index.html
deploy:
  local_dir: docs/wallet/
  provider: pages
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
env:
  global:
    secure: OfMfnEXkI0jSVQfuFFNwxYdtUxa0zrBQdSB0YUkWX2WD4VhXgAR7rPkUpCTDpXnLGkWZP3g695wDnQA5It9cCqUgpJmSsgomTb6xiw72y1agKUzq/pZWqa0XSbcjQBwQzuhTXJpd8hLUXiyvfJJMzPuY7wuIYk53hmDhAx8u9um0pK1N6XF92IL2v0oPMBg4mf65Bzf3IyE8ES5F2mxaa4ElF6bfv+1BLREy18wjBIUj0t7OjrplLCzZA9xhyJDFe1dnSDTCzK0wijoak0liLV9Ip+iKvnu3jVoMfhB009tEcT08GVfysETmH8UeEFoRbxozZL1zltNxOOMPIXsS54x+U8ODJrBQXM56Q7hB8ziEvECDbmHu4cp7FOdomiUzPOEa4606zaqYYpEsPFURwzQ1a3Q6x+1N4a0eey0XdsaVZbr0ZuLWtePJJQrbo4gH45GQlj7jXzVhR/sYq82dZ49y9i8jZPsdZeqsyHXy1bVg/XT1U1xW4asUhXS/6+qjZj5IuyJDHjY3bDmL0TEeqSRLQpJAWM+m+H/T9pzOSA7CU8/5LvuxvEETc1NRRtuC8ZjDfyVOn6XATaF/ddboXBPeD6g5IfIdf0R6tduMTG1b5sO7Q9y80aZ5PF/IpvlRrNWLxDrCcvAbzvJp9Qd/d1dAMaBuHJGj6xUQTAIxtz4=
